[colors.primary]
foreground = "#FFFFFF"

[font]
normal = { family = "JetBrainsMono Nerd Font", style = "Regular" } 
size = 14

[env]
TERM = "xterm-256color"

[shell]
program = "/bin/zsh"
args = ["-l"]
